/**
 * Git hook management — install/uninstall avifify as a git hook.
 *
 * Supports:
 *   - Direct .git/hooks/ installation
 *   - Husky v4+ integration (detects .husky/ directory)
 *   - Custom hooks directory (core.hooksPath)
 */

import { readFile, writeFile, chmod, mkdir, unlink } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

const HOOK_MARKER_START = '# >>> avifify pre-push hook >>>';
const HOOK_MARKER_END = '# <<< avifify pre-push hook <<<';

const HOOK_TYPES = ['pre-push', 'pre-commit'];

/**
 * Generate the hook script content.
 */
function hookScript(hookType) {
  return `${HOOK_MARKER_START}
# Auto-generated by avifify — do not edit between markers
npx avifify --staged-only
AVIFIFY_EXIT=$?
if [ $AVIFIFY_EXIT -ne 0 ]; then
  echo "avifify: image conversion failed or found unconverted images"
  echo "Run 'npx avifify' to convert images before pushing."
  exit 1
fi
# If images were converted, auto-stage them
git diff --name-only | grep '\\.avif$' | xargs -r git add
${HOOK_MARKER_END}`;
}

/**
 * Detect the git hooks directory.
 */
async function getHooksDir(cwd) {
  // Check for husky directory
  const huskyDir = resolve(cwd, '.husky');
  if (existsSync(huskyDir)) {
    return { type: 'husky', path: huskyDir };
  }

  // Check for custom hooksPath in git config
  try {
    const { stdout } = await execFileAsync('git', ['config', 'core.hooksPath'], { cwd });
    const customPath = stdout.trim();
    if (customPath) {
      return { type: 'custom', path: resolve(cwd, customPath) };
    }
  } catch {
    // No custom hooks path set
  }

  // Default to .git/hooks
  const gitHooksDir = resolve(cwd, '.git', 'hooks');
  if (existsSync(resolve(cwd, '.git'))) {
    return { type: 'git', path: gitHooksDir };
  }

  throw new Error('Not a git repository (no .git directory found)');
}

/**
 * Install the git hook.
 *
 * @param {object}  options
 * @param {string}  [options.hookType='pre-push']  - Hook type
 * @param {string}  [options.cwd=process.cwd()]    - Working directory
 * @param {object}  logger                         - Logger instance
 */
export async function installHook({ hookType = 'pre-push', cwd = process.cwd() } = {}, logger) {
  if (!HOOK_TYPES.includes(hookType)) {
    throw new Error(`Unsupported hook type: ${hookType}. Supported: ${HOOK_TYPES.join(', ')}`);
  }

  const { type, path: hooksDir } = await getHooksDir(cwd);
  await mkdir(hooksDir, { recursive: true });

  const hookPath = join(hooksDir, hookType);
  const script = hookScript(hookType);

  if (existsSync(hookPath)) {
    const existing = await readFile(hookPath, 'utf-8');

    // Already installed?
    if (existing.includes(HOOK_MARKER_START)) {
      // Replace existing avifify block
      const regex = new RegExp(
        `${escapeRegex(HOOK_MARKER_START)}[\\s\\S]*?${escapeRegex(HOOK_MARKER_END)}`,
        'm'
      );
      const updated = existing.replace(regex, script);
      await writeFile(hookPath, updated, 'utf-8');
      logger.success(`Updated avifify in existing ${hookType} hook (${type})`);
    } else {
      // Append to existing hook
      const updated = existing.trimEnd() + '\n\n' + script + '\n';
      await writeFile(hookPath, updated, 'utf-8');
      logger.success(`Appended avifify to existing ${hookType} hook (${type})`);
    }
  } else {
    // Create new hook file
    const content = `#!/usr/bin/env sh\n\n${script}\n`;
    await writeFile(hookPath, content, 'utf-8');
    logger.success(`Created ${hookType} hook at ${hookPath} (${type})`);
  }

  // Make executable
  await chmod(hookPath, 0o755);
  logger.info(`Hook installed via ${type} at ${hookPath}`);
}

/**
 * Uninstall the git hook (removes only the avifify block).
 */
export async function uninstallHook({ hookType = 'pre-push', cwd = process.cwd() } = {}, logger) {
  const { type, path: hooksDir } = await getHooksDir(cwd);
  const hookPath = join(hooksDir, hookType);

  if (!existsSync(hookPath)) {
    logger.warn(`No ${hookType} hook found at ${hookPath}`);
    return;
  }

  const existing = await readFile(hookPath, 'utf-8');

  if (!existing.includes(HOOK_MARKER_START)) {
    logger.warn(`No avifify block found in ${hookType} hook`);
    return;
  }

  const regex = new RegExp(
    `\\n?${escapeRegex(HOOK_MARKER_START)}[\\s\\S]*?${escapeRegex(HOOK_MARKER_END)}\\n?`,
    'm'
  );
  const cleaned = existing.replace(regex, '\n').trim();

  // If the hook only had our content, remove the file entirely
  const isShebangOnly = /^#!\/usr\/bin\/env\s+sh\s*$/m.test(cleaned) && cleaned.split('\n').filter(l => l.trim()).length <= 1;

  if (!cleaned || isShebangOnly) {
    await unlink(hookPath);
    logger.success(`Removed ${hookType} hook entirely (was only avifify)`);
  } else {
    await writeFile(hookPath, cleaned + '\n', 'utf-8');
    await chmod(hookPath, 0o755);
    logger.success(`Removed avifify block from ${hookType} hook`);
  }
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
